# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

$:.push File.expand_path("../lib", __FILE__)
require "polar_client/version"

Gem::Specification.new do |s|
  s.name = "polar_client"
  s.version = PolarClient::VERSION
  s.platform = Gem::Platform::RUBY
  s.authors = ["OpenAPI-Generator"]
  s.email = ["b2bhelpdesk@polar.com"]
  s.homepage = "https://openapi-generator.tech"
  s.summary = "Polar Accesslink API Ruby Gem"
  s.description = "Polar Accesslink API documentation"
  s.license = "Unlicense"
  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency "typhoeus", "~> 1.0", ">= 1.0.1"

  s.add_development_dependency "rspec", "~> 3.6", ">= 3.6.0"

  s.files = `git ls-files`.split($/)
  s.executables = []
  s.require_paths = ["lib"]
end
