# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"

# Unit tests for PolarClient::ContinuousHeartRateBetaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "ContinuousHeartRateBetaApi" do
  before do
    # run before each test
    @api_instance = PolarClient::ContinuousHeartRateBetaApi.new
  end

  after do
    # run after each test
  end

  describe "test an instance of ContinuousHeartRateBetaApi" do
    it "should create an instance of ContinuousHeartRateBetaApi" do
      expect(@api_instance).to be_instance_of(PolarClient::ContinuousHeartRateBetaApi)
    end
  end

  # unit tests for v3_users_continuous_heart_rate_date_get
  # Get Continuous Heart rate samples
  # Get users continuous heart rate values for given date. &lt;a href&#x3D;\&quot;https://support.polar.com/en/support/the_what_and_how_of_polars_continuous_heart_rate\&quot;&gt; Supported devices &lt;/a&gt;
  # @param date Date of Continuous Heart Rate as ISO-8601 date string, example: \&quot;2022-01-01\&quot;
  # @param [Hash] opts the optional parameters
  # @return [ContinuousHeartrate]
  describe "v3_users_continuous_heart_rate_date_get test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v3_users_continuous_heart_rate_get
  # Get Continuous Heart rate samples with range
  # Get users continuous heart rate values for given date range. &lt;a href&#x3D;\&quot;https://support.polar.com/en/support/the_what_and_how_of_polars_continuous_heart_rate\&quot;&gt; Supported devices &lt;/a&gt;
  # @param from Inclusive start date of range as ISO-8601 date string, example: \&quot;2022-01-01\&quot;
  # @param to Inclusive end date of range as ISO-8601 date string, example: \&quot;2022-01-28\&quot;
  # @param [Hash] opts the optional parameters
  # @return [ContinuousHeartrate]
  describe "v3_users_continuous_heart_rate_get test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
