# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"

# Unit tests for PolarClient::ExercisesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "ExercisesApi" do
  before do
    # run before each test
    @api_instance = PolarClient::ExercisesApi.new
  end

  after do
    # run after each test
  end

  describe "test an instance of ExercisesApi" do
    it "should create an instance of ExercisesApi" do
      expect(@api_instance).to be_instance_of(PolarClient::ExercisesApi)
    end
  end

  # unit tests for get_exercise_fit_without_transaction
  # Get exercise FIT
  # FIT file for users exercise. Only Exercises uploaded to Flow in the last 30 days are available. Only exercises that have been uploaded to Flow after the user is registered with your client will be available. See [FIT sport mappings in appendix](#sport-type-mapping-in-fit-files).
  # @param exercise_id Hashed exercise id.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe "get_exercise_fit_without_transaction test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_exercise_gpx_without_transaction
  # Get exercise GPX
  # GPX file for users exercise without an Accesslink \&quot;transaction\&quot;. Only Exercises uploaded to Flow in the last 30 days are available. Only exercises that have been uploaded to Flow after the user is registered with your client will be available.
  # @param exercise_id Hashed exercise id.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe "get_exercise_gpx_without_transaction test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_exercise_tcx_without_transaction
  # Get exercise TCX
  # TCX file for users exercise without an Accesslink \&quot;transaction\&quot;. Only Exercises uploaded to Flow in the last 30 days are available. Only exercises that have been uploaded to Flow after the user is registered with your client will be available.
  # @param exercise_id Hashed exercise id.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe "get_exercise_tcx_without_transaction test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_exercise_without_transaction
  # Get exercise
  # Get users exercise using hashed id. Only Exercises uploaded to Flow in the last 30 days are available. Only exercises that have been uploaded to Flow after the user is registered with your client will be available. Use samples and zones query parameters to return optional samples and zone information of the exercise.
  # @param exercise_id Hashed exercise id.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :samples Return all sample data for this exercise.
  # @option opts [Boolean] :zones Return all zones data for this exercise.
  # @return [ExerciseHashId]
  describe "get_exercise_without_transaction test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_exercises_without_transaction
  # List exercises
  # List users exercises available in Accesslink. Only Exercises uploaded to Flow in the last 30 days are returned. Only exercises that have been uploaded to Flow after the user is registered with your client will be returned. Use samples and zones query parameters to return optional samples and zone information of the exercises. Training Load Pro data will be included in the exercise object if the exercise is recorded with a specific wrist unit model,  please check [compatible devices](https://www.polar.com/en/smart-coaching/training-load-pro) for more information.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :samples Return all sample data for this exercise.
  # @option opts [Boolean] :zones Return all zones data for this exercise.
  # @return [Array<ExerciseHashId>]
  describe "list_exercises_without_transaction test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
