# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"

# Unit tests for PolarClient::NightlyRechargeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "NightlyRechargeApi" do
  before do
    # run before each test
    @api_instance = PolarClient::NightlyRechargeApi.new
  end

  after do
    # run after each test
  end

  describe "test an instance of NightlyRechargeApi" do
    it "should create an instance of NightlyRechargeApi" do
      expect(@api_instance).to be_instance_of(PolarClient::NightlyRechargeApi)
    end
  end

  # unit tests for list_nightly_recharge
  # List Nightly Recharges
  # List Nightly Recharge data of user for the last 28 days.
  # @param [Hash] opts the optional parameters
  # @return [Recharges]
  describe "list_nightly_recharge test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v3_users_nightly_recharge_date_get
  # Get Nightly Recharge
  # Get Users Nightly Recharge data for given date.
  # @param date Date of Nightly Recharge as ISO-8601 date string, example: \&quot;2020-01-01\&quot;
  # @param [Hash] opts the optional parameters
  # @return [NightlyRecharge]
  describe "v3_users_nightly_recharge_date_get test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
