# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"

# Unit tests for PolarClient::PullNotificationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "PullNotificationsApi" do
  before do
    # run before each test
    @api_instance = PolarClient::PullNotificationsApi.new
  end

  after do
    # run after each test
  end

  describe "test an instance of PullNotificationsApi" do
    it "should create an instance of PullNotificationsApi" do
      expect(@api_instance).to be_instance_of(PolarClient::PullNotificationsApi)
    end
  end

  # unit tests for list
  # List
  # Get list of available exercises and activities for users
  # @param [Hash] opts the optional parameters
  # @return [AvailableUserDatas]
  describe "list test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
