# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"

# Unit tests for PolarClient::SleepApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "SleepApi" do
  before do
    # run before each test
    @api_instance = PolarClient::SleepApi.new
  end

  after do
    # run after each test
  end

  describe "test an instance of SleepApi" do
    it "should create an instance of SleepApi" do
      expect(@api_instance).to be_instance_of(PolarClient::SleepApi)
    end
  end

  # unit tests for list_nights
  # List nights
  # List sleep data of user for the last 28 days.
  # @param [Hash] opts the optional parameters
  # @return [Nights]
  describe "list_nights test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v3_users_sleep_available_get
  # Get available sleep times
  # Get the dates with sleep start and end times, where user has sleep data available in the last 28 days.
  # @param [Hash] opts the optional parameters
  # @return [AvailableSleeps]
  describe "v3_users_sleep_available_get test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v3_users_sleep_date_get
  # Get Sleep
  # Get Users sleep data for given date.
  # @param date Date of sleep as ISO-8601 date string, example: \&quot;2020-01-01\&quot;
  # @param [Hash] opts the optional parameters
  # @return [Sleep]
  describe "v3_users_sleep_date_get test" do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
