# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for PolarClient::ActivityLog
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarClient::ActivityLog do
  let(:instance) { PolarClient::ActivityLog.new }

  describe "test an instance of ActivityLog" do
    it "should create an instance of ActivityLog" do
      expect(instance).to be_instance_of(PolarClient::ActivityLog)
    end
  end
  describe 'test attribute "activity_log"' do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
