# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for PolarClient::AvailableUserData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarClient::AvailableUserData do
  let(:instance) { PolarClient::AvailableUserData.new }

  describe "test an instance of AvailableUserData" do
    it "should create an instance of AvailableUserData" do
      expect(instance).to be_instance_of(PolarClient::AvailableUserData)
    end
  end
  describe 'test attribute "user_id"' do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data_type"' do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["EXERCISE", "ACTIVITY_SUMMARY", "PHYSICAL_INFORMATION"])
      # validator.allowable_values.each do |value|
      #   expect { instance.data_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "url"' do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
