# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for PolarClient::CardioLoadStatusEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarClient::CardioLoadStatusEnum do
  let(:instance) { PolarClient::CardioLoadStatusEnum.new }

  describe "test an instance of CardioLoadStatusEnum" do
    it "should create an instance of CardioLoadStatusEnum" do
      expect(instance).to be_instance_of(PolarClient::CardioLoadStatusEnum)
    end
  end
end
