# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for PolarClient::ContinuousHeartrate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarClient::ContinuousHeartrate do
  let(:instance) { PolarClient::ContinuousHeartrate.new }

  describe "test an instance of ContinuousHeartrate" do
    it "should create an instance of ContinuousHeartrate" do
      expect(instance).to be_instance_of(PolarClient::ContinuousHeartrate)
    end
  end
  describe 'test attribute "polar_user"' do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "date"' do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "heart_rate_samples"' do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
