# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for PolarClient::PhysicalInformations
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarClient::PhysicalInformations do
  let(:instance) { PolarClient::PhysicalInformations.new }

  describe "test an instance of PhysicalInformations" do
    it "should create an instance of PhysicalInformations" do
      expect(instance).to be_instance_of(PolarClient::PhysicalInformations)
    end
  end
  describe 'test attribute "physical_informations"' do
    it "should work" do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
