# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for PolarClient::TrainingLoadProLoadEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarClient::TrainingLoadProLoadEnum do
  let(:instance) { PolarClient::TrainingLoadProLoadEnum.new }

  describe "test an instance of TrainingLoadProLoadEnum" do
    it "should create an instance of TrainingLoadProLoadEnum" do
      expect(instance).to be_instance_of(PolarClient::TrainingLoadProLoadEnum)
    end
  end
end
