# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"
require "json"
require "date"

# Unit tests for PolarClient::WebhookType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PolarClient::WebhookType do
  let(:instance) { PolarClient::WebhookType.new }

  describe "test an instance of WebhookType" do
    it "should create an instance of WebhookType" do
      expect(instance).to be_instance_of(PolarClient::WebhookType)
    end
  end
end
