# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

# Common files
require "polar_client/api_client"
require "polar_client/api_error"
require "polar_client/version"
require "polar_client/configuration"

# Models
require "polar_client/models/activity"
require "polar_client/models/activity_log"
require "polar_client/models/activity_step_sample"
require "polar_client/models/activity_step_samples"
require "polar_client/models/activity_zone_sample"
require "polar_client/models/activity_zone_samples"
require "polar_client/models/alertness"
require "polar_client/models/alertness_hourly_data"
require "polar_client/models/available_sleep"
require "polar_client/models/available_sleeps"
require "polar_client/models/available_user_data"
require "polar_client/models/available_user_datas"
require "polar_client/models/cardio_load"
require "polar_client/models/cardio_load_levels"
require "polar_client/models/cardio_load_status_enum"
require "polar_client/models/circadian_bedtime"
require "polar_client/models/continuous_heartrate"
require "polar_client/models/continuous_heartrate_heart_rate_samples"
require "polar_client/models/created_webhook"
require "polar_client/models/created_webhook_data"
require "polar_client/models/duration_zone"
require "polar_client/models/error"
require "polar_client/models/exercise"
require "polar_client/models/exercise_hash_id"
require "polar_client/models/exercises"
require "polar_client/models/heart_rate"
require "polar_client/models/nightly_recharge"
require "polar_client/models/nights"
require "polar_client/models/physical_information"
require "polar_client/models/physical_informations"
require "polar_client/models/recharges"
require "polar_client/models/register"
require "polar_client/models/sample"
require "polar_client/models/samples"
require "polar_client/models/sleep"
require "polar_client/models/training_load_pro_load_enum"
require "polar_client/models/training_load_pro_rpe_enum"
require "polar_client/models/training_load_pro_sample"
require "polar_client/models/transaction_location"
require "polar_client/models/user"
require "polar_client/models/user_extra_info"
require "polar_client/models/webhook_info"
require "polar_client/models/webhook_info_data"
require "polar_client/models/webhook_patch"
require "polar_client/models/webhook_payload_alertness"
require "polar_client/models/webhook_payload_circadian_bedtime"
require "polar_client/models/webhook_payload_continuous_heart_rate"
require "polar_client/models/webhook_payload_exercise"
require "polar_client/models/webhook_payload_sleep"
require "polar_client/models/webhook_ping"
require "polar_client/models/webhook_request"
require "polar_client/models/webhook_type"
require "polar_client/models/zone"
require "polar_client/models/zones"

# APIs
require "polar_client/api/cardio_load_beta_api"
require "polar_client/api/continuous_heart_rate_beta_api"
require "polar_client/api/daily_activity_api"
require "polar_client/api/exercises_api"
require "polar_client/api/nightly_recharge_api"
require "polar_client/api/physical_info_api"
require "polar_client/api/pull_notifications_api"
require "polar_client/api/sleep_api"
require "polar_client/api/sleep_wisetrade_beta_api"
require "polar_client/api/training_data_api"
require "polar_client/api/users_api"
require "polar_client/api/webhooks_api"

module PolarClient
  class << self
    # Customize default settings for the SDK using block.
    #   PolarClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
