# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "spec_helper"

describe PolarClient::Configuration do
  let(:config) { PolarClient::Configuration.default }

  before(:each) do
    # uncomment below to setup host and base_path
    # require 'URI'
    # uri = URI.parse("https://www.polaraccesslink.com")
    # PolarClient.configure do |c|
    #   c.host = uri.host
    #   c.base_path = uri.path
    # end
  end

  describe "#base_url" do
    it "should have the default value" do
      # uncomment below to test default value of the base path
      # expect(config.base_url).to eq("https://www.polaraccesslink.com")
    end

    it "should remove trailing slashes" do
      [nil, "", "/", "//"].each do |base_path|
        config.base_path = base_path
        # uncomment below to test trailing slashes
        # expect(config.base_url).to eq("https://www.polaraccesslink.com")
      end
    end
  end
end
