# #Polar Accesslink API
#
# Polar Accesslink API documentation
#
# The version of the OpenAPI document: 3
# Contact: b2bhelpdesk@polar.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.6.0
#

require "date"
require "time"

module PolarClient
  class TrainingLoadProRpeEnum
    UNKNOWN = "UNKNOWN".freeze
    RPE_NONE = "RPE_NONE".freeze
    RPE_EASY = "RPE_EASY".freeze
    RPE_LIGHT = "RPE_LIGHT".freeze
    RPE_FAIRLY_BRISK = "RPE_FAIRLY_BRISK".freeze
    RPE_BRISK = "RPE_BRISK".freeze
    RPE_MODERATE = "RPE_MODERATE".freeze
    RPE_FAIRLY_HARD = "RPE_FAIRLY_HARD".freeze
    RPE_HARD = "RPE_HARD".freeze
    RPE_EXHAUSTING = "RPE_EXHAUSTING".freeze
    RPE_EXTREME = "RPE_EXTREME".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, RPE_NONE, RPE_EASY, RPE_LIGHT, RPE_FAIRLY_BRISK, RPE_BRISK, RPE_MODERATE, RPE_FAIRLY_HARD, RPE_HARD, RPE_EXHAUSTING, RPE_EXTREME].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if TrainingLoadProRpeEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #TrainingLoadProRpeEnum"
    end
  end
end
